# Generated by Django 3.2.9 on 2021-11-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_quantity', models.IntegerField(verbose_name='Entry quantity')),
                ('order_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.stock')),
            ],
        ),
    ]
