# Generated by Django 3.2.9 on 2021-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='entry_quantity',
            field=models.PositiveIntegerField(verbose_name='Entry quantity'),
        ),
    ]
