# Generated by Django 3.2.9 on 2021-11-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
