# Generated by Django 3.2.9 on 2021-11-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_container', '0003_alter_favorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stocks',
            new_name='stock',
        ),
    ]
