# Generated by Django 3.2.9 on 2021-11-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_container', '0004_rename_stocks_inventory_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
