# Generated by Django 3.2.9 on 2021-11-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Value')),
                ('date_of_change', models.DateTimeField(verbose_name='Date of change')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('details', models.TextField(blank=True, max_length=512, null=True, verbose_name='Details')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='stock_management.price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
